### PR TITLE
Docker image

### PR DESCRIPTION
**Pull request by vkazanov**
Introduce a basic Docker CubeDB image.

### CODE REVIEW

**Comment by sztanko** [comment]
Wouldn't this be better if the jar was built as part of building image?

**Comment by vkazanov** [comment]
Nope. It's one thing to have JRE only within the container, another - to have JDK with all the dependencies. It's much cleaner to build the image having only JRE + the jar file inside.

**Comment by expobrain** [comment]
What about another image which just builds the jar?

**Comment by vkazanov** [comment]
@expobrain I'll leave that as an exercise for interested people :-)

**Pull request merged**
